# Netlify configuration for Vite React app
[build]
  publish = "fin/dist"
  command = "cd fin && npm install && npm run build"

[redirects]
  [[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

# Uncomment below for SPA routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
